micronaut:
  application:
    name: octopusDemo
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/octopus`}
    username: ${JDBC_USER:octopus}
    password: ${JDBC_PASSWORD:password}
jpa:
  default:
    reactive: true
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: none
        connection:
          url: ${datasources.default.url}
          username: ${datasources.default.username}
          password: ${datasources.default.password}
flyway:
  datasources:
    default:
      enabled: false